name: Build Payload Dumper Go

on:
  workflow_dispatch:

jobs:
  build:
    name: Cross-Compile
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y liblzma-dev

      - name: Clone payload-dumper-go
        run: |
          git clone https://github.com/ssut/payload-dumper-go.git
          cd payload-dumper-go

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'  # Use the latest Go version
          
      - name: Set CGO environment variables
        run: |
          export CGO_ENABLED=1
          export CGO_CFLAGS="-I/usr/include"
          export CGO_LDFLAGS="-L/usr/lib"

      - name: Clean and download dependencies
        run: |
          cd payload-dumper-go
          go mod tidy
          
      - name: Build binary
        run: |
          cd payload-dumper-go
          mkdir -p build
          CGO_ENABLED=1 GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o build/payload-dumper-${{ matrix.goos }}-${{ matrix.goarch }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: payload-dumper-${{ matrix.goos }}-${{ matrix.goarch }}
          path: payload-dumper-go/build/payload-dumper-*
