name: Extract Payload.bin, Boot.img, and Vbmeta.img

on:
  workflow_dispatch:
    inputs:
      rom_url:
        description: 'URL to the stock ROM .zip file'
        required: true
        type: string

jobs:
  extract-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip tar

    - name: Download payload-dumper-go
      run: |
        wget https://github.com/ssut/payload-dumper-go/releases/download/1.3.0/payload-dumper-go_1.3.0_linux_amd64.tar.gz
        tar -xvf payload-dumper-go_1.3.0_linux_amd64.tar.gz
        chmod +x payload-dumper-go
        # Add payload-dumper-go to PATH
        export PATH=$PATH:$PWD

    - name: Download Stock ROM
      run: |
        echo "Downloading stock ROM from ${GITHUB_EVENT_INPUTS_ROM_URL}"
        wget -O stock_rom.zip "${{ github.event.inputs.rom_url }}"

    - name: Extract Stock ROM
      run: |
        mkdir extracted_rom
        unzip stock_rom.zip -d extracted_rom

    - name: Extract Payload.bin
      run: |
        # Use payload-dumper-go to extract payload.bin
        mkdir output
        payload-dumper-go extracted_rom/payload.bin /output

    - name: List Extracted Files output 
      run: ls -l /output

    - name: List Extracted Files extracted_rom
      run: ls -l /extracted_rom

    - name: List Extracted Files di
      run: ls

    - name: Extract boot.img and vbmeta.img
      run: |
        # Search for boot.img and vbmeta.img in the extracted ROM directory
        find output -name "boot.img" -exec cp {} ./ \;
        find output -name "vbmeta.img" -exec cp {} ./ \;

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: extracted-files
        path: |
          output/
          boot.img
          vbmeta.img
          
