name: Extract Boot Image

on:
  watch:
    types: [started]
  workflow_dispatch:

jobs:
  extract-boot-img:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Environment
      run: sudo apt-get update && sudo apt-get install -y unzip

    - name: Download Stock ROM
      # Replace with your actual ROM URL or path in the repo
      run: wget -O stock_rom.zip "https://cdnorg.d.miui.com/OS1.0.9.0.UNLIDXM/miui_DUCHAMPIDGlobal_OS1.0.9.0.UNLIDXM_80bea8031a_14.0.zip"

    - name: Extract Boot Image
      run: |
        mkdir extracted_rom
        unzip stock_rom.zip -d extracted_rom
        find extracted_rom -name "boot.img" -exec cp {} . \;

    - name: Upload Boot Image Artifact
      uses: actions/upload-artifact@v3
      with:
        name: boot.img
        path: boot.img
        
