name: Extract Boot Image

on:
  workflow_dispatch:
    inputs:
      rom_url:
        description: 'INPUT URL LINK DOWNLOAD'
        required: true
        type: string

jobs:
  extract-boot-img:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Environment
      run: sudo apt-get update && sudo apt-get install -y unzip

    - name: Download Stock ROM
      # Replace with your actual ROM URL or path in the repo
      run: wget -O stock_rom.zip "${{ github.event.inputs.rom_url }}"

    - name: Extract Boot Image
      run: |
        mkdir extracted_rom
        unzip stock_rom.zip -d extracted_rom
        find extracted_rom -name "boot.img" -exec cp {} . \;

    - name: Upload Boot Image Artifact
      uses: actions/upload-artifact@v3
      with:
        name: boot.img
        path: boot.img
        
